<?php
/*
Plugin Name: o2switch - WpTiger
Description: Ce plugin est généré par l'outil WpTiger de cPanel et ajoute des règles (snippets) à votre site WordPress.
License:     GPL2
Plugin URI:  https://faq.o2switch.fr/
Version:     19-06-22
*/

// Ne modifiez pas ce fichier, vos modifications seront écrasés car ce fichier est généré dynamiquement par l'outil
// WPTiger sur cPanel.
// Do not edit this file, your modifications will be lost because this file is auto-generated by the WPTiger tool

defined( 'ABSPATH' ) or die( 'No direct file access allowed!' );

// o2s WpTiger - removeWpVersion
// Masque la version de WordPress
function o2_remove_wordpress_version() {
    return '';
}
function o2_remove_version_from_style_js( $src ) {
    if ( strpos( $src, 'ver=' . get_bloginfo( 'version' ) ) ){
        $src = remove_query_arg( 'ver', $src );
    }
    return $src;
}

add_filter( 'style_loader_src', 'o2_remove_version_from_style_js');
add_filter( 'script_loader_src', 'o2_remove_version_from_style_js');
add_filter('the_generator', 'o2_remove_wordpress_version');
